//
//  CorePluginError.swift
//  NMSDK
//
//  Created by Francesco Colleoni on 28/04/16.
//  Copyright © 2016 Near srl. All rights reserved.
//

import Foundation
import NMJSON
import NMPlug

/**
 Represents an error generated by a core plugin used by NearSDK.
 */
@objc
public class CorePluginError: NSObject {
    // MARK: Properties
    /**
     The core plugin.
     
     - seealso: `CorePlugin`
     */
    public private (set) var plugin: CorePlugin!
    
    /**
     The error.
     
     - seealso: `NearSDKError`
     */
    public private (set) var error: NearSDKError!
    
    /**
     A message associated to the error.
     */
    public private (set) var message = ""
    
    // MARK: Initializers
    /**
     Initializes a new `CorePluginError`.
    
     - parameter event: the source PluginEvent instance which represents the error; it must include fields `message` (`String`) and `error` (`Int`, convertible to a `NearSDKError` case), `event.from` must be convertible into a `CorePlugin` case
     */
    public init?(event: PluginEvent) {
        super.init()
        
        guard let
            sourcePlugin = CorePlugin(name: event.from),
            errorValue = event.content.int("error"), sourceError = NearSDKError(rawValue: errorValue), sourceErrorMessage = event.content.string("message") else {
            return nil
        }
        
        plugin = sourcePlugin
        error = sourceError
        message = sourceErrorMessage
    }
    
    // MARK: Properties
    /**
     Human-readable description of `Self`.
     */
    public override var description: String {
        return Console.describe(CorePluginError.self, properties: ("plugin", plugin.description), ("error", error.description), ("message", message))
    }
}
