//
//  NearSDKDelegate.swift
//  NMSDK
//
//  Created by Francesco Colleoni on 08/04/16.
//  Copyright © 2016 Near srl. All rights reserved.
//

import Foundation
import NMNet
import NMPlug

/// The protocol which should be implemented by classes which should receive and consume events generated by `NearSDK`.
@objc
public protocol NearSDKDelegate {
    // MARK: Common methods
    /// This method is executed whenever `NearSDK` receives an event.
    ///
    /// - parameters:
    ///   - event: the event received by `NearSDK`
    optional func nearSDKDidReceiveEvent(event: PluginEvent)
    
    /// This method is executed whenever `NearSDK` detects an error.
    ///
    /// - parameters:
    ///   - error: the `NearSDKError` received by `NearSDK`
    ///   - message: a `String` which better describes the error
    optional func nearSDKDidFail(error error: NearSDKError, message: String)
    
    // MARK: Evaluating reactions
    /// This method is executed whenever `NearSDK` evaluates one or more notification reactions.
    /// 
    /// - parameters:
    ///   - notifications: notification reactions evaluated by `NearSDK`
    optional func nearSDKDidEvaluate(notifications collection: [Notification])
    
    /// This method is executed whenever `NearSDK` evaluates one or more content reactions.
    /// 
    /// - parameters:
    ///   - contents: content reactions evaluated by `NearSDK`
    optional func nearSDKDidEvaluate(contents collection: [Content])
    
    /// This method is executed whenever `NearSDK` evaluates one or more poll reactions.
    ///
    /// - parameters:
    ///   - polls: poll reactions evaluated by `NearSDK`
    optional func nearSDKDidEvaluate(polls collection: [Poll])
}
